name: steelseries-engine
version: "1.0"
author: Andrea Coronese <sixpounder@protonmail.com>
about: Control your Steelseries devices through the command line
args:
    - timeout:
        long: timeout
        short: t
        help: The maximum time to wait (in milliseconds) for each response from the device
    - dry:
        long: dry
        short: d
        help: Executes a dry run, meaning no data will effecively be written to any device
    - verbose:
        long: verbose
        short: v
        help: Sets the level of verbosity
    - escalate:
        long: escalate
        short: e
        help: Internally escalate privileges if needed, prompting the user for authentication
subcommands:
    - describe:
        version: "1.0"
        about: Displays a list of a single device capabilities and configurable properties
        args:
            - device:
                index: 1
                required: true
                value_name: device,
                help: Specifies a device to inspect
    - list:
        version: "1.0"
        about: Lists supported devices connected to the host
    - supported:
        version: "1.0"
        about: Lists supported devices, even if not connected to the host
    - change:
        version: "1.0"
        about: Changes configuration for a device
        args:
            - save:
                long: save
                short: s
                help: Saves edits to the device internal memory
            - device:
                index: 1
                required: true
                value_name: device
                help: Specifies a device to manipulate
            - PROPERTY:
                index: 2
                required: true
                value_name: PROPERTY
                help: Specifies what property to manipulate (eg. a led color). Properties support varies per device, use the 'describe' command to inspect a single device for supported properties
            - VALUE:
                index: 3
                required: true
                value_name: VALUE
                help: The property value to set
